### ISSUE TITLE
Anarchy/Democracy??

### ISSUE THREAD

**Issue by Krushchevawn** [aidanrwt/twitch-plays#4]
Is there Any plan to add anarchy/democracy slider or do you have any idea how to add the anarchy/democracy slider?

**Comment by ynohtna92** [comment]
I can do this in my fork if you would like to assign me @aidraj .

**Comment by aidanrwt** [comment]
Go ahead ynohtna92. I wrote up a class for handling/drawing the bar already before, don't think I kept a backup of it. I'm not a big fan of the anarchy/democracy mode.

**Comment by Krushchevawn** [comment]
Will the Anarchy and Dempcracy thing be ready anytime soon? No rush. Id just really like to have it. Im interested in it for my streams!

**Comment by ynohtna92** [comment]
Soon^tm.

Expect to see it to see it latest 24 hours from now. I'll try to work on it today if I have some time.

**Comment by ynohtna92** [comment]
Almost done. Just need to put on those silly arrows 
![image](https://f.cloud.github.com/assets/2245318/2239793/8c573e4c-9c56-11e3-8ca3-a306d82add7f.png)

Don't mind the positioning, Just testing now.

**Comment by Krushchevawn** [comment]
Is it possible you can show me to set the chat up and stuff just like that. Im just using screen regions for my stuff right now and its all over the place.

**Comment by ynohtna92** [comment]
![image](https://f.cloud.github.com/assets/2245318/2239841/5deb0842-9c5e-11e3-95ee-0d51e547672d.png)

Something like that, obviously it needs more tuning to make it fit right.

**Comment by Krushchevawn** [comment]
Anyway you could help me with something like this?

**Comment by Krushchevawn** [comment]
Not trying to be demanding or anything. id just like some help since im gonna use the anarchy and democracy i have no place to put it. So thats why i was asking if you couls help me set something up like this. So i can actually have room to place it.

**Comment by ynohtna92** [comment]
https://github.com/ynohtna92/twitch-plays/commit/70cf65b5d0f00132955e4d2460d5e61f9d25cf7b

Updated my fork. It should fit nicely in a 16:9 broadcast window along side the square pokemon window.

![image](https://f.cloud.github.com/assets/2245318/2243502/bd305ed2-9d2c-11e3-973d-27cf3980dca7.png)

**Comment by moieza** [comment]
Hello ynohtna92,
Sry for my english
I can not launch twitchplays.py on your repo : 

Traceback (most recent call last):
  File "C:\Users\Polzy\Desktop\twitch-plays-master\TwitchPlays.py", line 12, in <module>
    import lib.bot as bot
  File "C:\Users\Polzy\Desktop\twitch-plays-master\lib\bot.py", line 1, in <module>
    from ircbot import Irc
  File "C:\Users\Polzy\Desktop\twitch-plays-master\lib\ircbot.py", line 1, in <module>
    import irc.bot
ImportError: No module named irc.bot

**Comment by moieza** [comment]
How to install IRC Client and Tornado for Windows ?

**Comment by ynohtna92** [comment]
Download each dependency. 

Unzip the the folder and find the setup file.

Locate this directory in cmd and run the command 'python setup.py install'. 
(python should be where your installation is, so for example I would run 'C:/Python27/python.exe setup.py install')

Do this for each dependency.

**Comment by Krushchevawn** [comment]
I have it all installed but its really messed up it seems it shows this on the web interface and has errors! 
![ss 2014-02-24 at 03 50 11](https://f.cloud.github.com/assets/6749530/2250889/6672c120-9d95-11e3-9c6d-10486250ba20.png) 
![ss 2014-02-24 at 03 50 32](https://f.cloud.github.com/assets/6749530/2250890/685386a0-9d95-11e3-974b-4c3daaca4e2f.png)

**Comment by ynohtna92** [comment]
Oh forgot to add file references.. sorry I'll fix it now.

**Comment by ynohtna92** [comment]
https://github.com/ynohtna92/twitch-plays/commit/4419a2b4914942697535803e61b97ba2e7ba32d9

Try again with this. It may still give a favicon warning but don't worry about it.

**Comment by Krushchevawn** [comment]
Well it worked. but now how do i get the time to start from 0?

**Comment by ynohtna92** [comment]
In the file "lib/template/index.html" on line 190.

```
var start = new Date(1392947369 * 1000);
```

Change the 1392947369 to your starting epoch time stamp. You can make one here http://www.epochconverter.com/. I'll eventually add in a better way to do this.

**Comment by Krushchevawn** [comment]
How would i go about adjusting the web socket to look appropriate on the stream because right now it has the browser border around it and stuff and i dont know how to remove that. How would you go about doing that?

**Comment by ynohtna92** [comment]
![image](https://f.cloud.github.com/assets/2245318/2254015/064c8264-9dcb-11e3-8791-1a30ed1e130c.png)

You have to use the sub region setting. You can get to this by right clicking on the source and selecting property. Then enable sub regions and click the 'Select Region' Button to create a window around the black box. After that is done you can resize to your liking using Edit Scene in OBS.

**Comment by Krushchevawn** [comment]
Okay and with the democracy and anarchy how many times would one have to say it before it goes to democracy i said democracy twice but Anarchy is still highlighted?

**Comment by ynohtna92** [comment]
Change the config anarchy-democracy setting to a smaller number (50 perhaps). It always start in anarchy mode. The bar will move 1 point left or right depending on what is said, so it will take 16 democracy votes to change it with a size of 50 from starting the program. 

You will also have to remove the '500 #' on line 40 of the bot.py file. I forgot to commit that change.

**Comment by MrMcain** [comment]
Hello, I can not install the dependencies, can you help me?

**Comment by AUmrysh** [comment]
Are you using pip and virtualenv?

**Comment by MrMcain** [comment]
Ok I found pip and i installed all programs :) Thanks ! (Sorry for my english)

**Comment by AUmrysh** [comment]
Good to see you got it installed.  You don't need virtualenv, but it's a great tool to use with python in case you plan on installing multiple versions of python or multiple versions of libraries.

Technically, pip should be all you need to get twitch-plays working, so if you're not interested in learning virtualenv now, that is alright.

**Comment by wreck3d** [comment]
@ynohtna92, not sure how to contact you, but:
I currently am using aidraj's TPP clone and I stumbled upon this page (for the modes).
How can I add the feature where if someone types any of the directional commands (up, down, etc) it shows a tiny arrow to the direction they typed in the chat?

**Comment by ynohtna92** [comment]
There are a couple of ways you could do this but the quickest would be just changing https://github.com/ynohtna92/twitch-plays/blob/master/lib/template/index.html#L293-310 so if the string is equal to up,down,left,right it will return a html tagged image with the corresponding arrow.

**Comment by wreck3d** [comment]
I'm familiar with some coding stuff, but how would I change those lines to
make it point to an image? I know the basic HTML <img> tags or whatever,
but not sure where exactly to change stuff in those lines. Big help,
though, and hopefully you could answer this question as well :)
Also, how would I integrate that template into sunshinekitty's TPP clone?:
https://github.com/sunshinekitty/TwitchPlaysPokemon/tree/master/TwitchPlaysBot
Her/His clone is the only one I've actually been able to get working for
me. Thanks!

On Sun, May 17, 2015 at 1:24 AM, ynohtna92 notifications@github.com wrote:

> There are a couple of ways you could do this but the quickest would be
> just changing
> https://github.com/ynohtna92/twitch-plays/blob/master/lib/template/index.html#L293-310
> so if the string is equal to up,down,left,right it will return a html
> tagged image with the corresponding arrow.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/aidraj/twitch-plays/issues/4#issuecomment-102749494.

## 

-Branden-

**Comment by ynohtna92** [comment]
``` javascript
function formatOutput(left, right){
  var buffer_size = 20;
  var buffer_used = 0;
  var whitespace_size = 1;
  var img = "";

  if (left == "down"){
    left = " " // Clear instruction
    img = '<img src="downarrow.png" height="16" width="16">'
  }

  buffer_used = right.toString().length + whitespace_size;
  var buffer_left = buffer_size - buffer_used;
  if (buffer_left > left.length) {
    whitespace_size += buffer_left - left.length;
  }
  var left_end = buffer_left;
  left = left.substring(0, left_end);
  return img + left + Array(whitespace_size + 1).join(" ") + right;
};
```

Would be what the function turns into. Note this is untested.

As for sunshines clone, i have no idea. Mine should work as long as you have configured it correctly and you have the required dependencies installed.

**Comment by wreck3d** [comment]
For some reason, I kept getting this error with yours. Picture attached. (Sent from e-mail)

**Comment by wreck3d** [comment]
.

**Comment by ynohtna92** [comment]
```
left = " " // Clear instruction
img = '<img src="downarrow.png" height="16" width="16">'
```

Opps these lines should be

```
left = " "; // Clear instruction
img = '<img src="downarrow.png" height="16" width="16">';
```

But yeah you will need to actually add in the image so it can be referenced.

And what errors are you getting you didn't submit any photo.

**Comment by wreck3d** [comment]
I cannot get your bot to start, though. Whenever I type "twitchplays.py" to start it, I get this:

EDIT: Also, would I just copy & paste the code below four times for each direction icon?
![unnamed](https://cloud.githubusercontent.com/assets/10440098/7670981/52580f30-fc88-11e4-93bd-178da7a77c9a.png)

Code:
  if (left == "down"){
  left = " "; // Clear instruction
  img = '<img src="downarrow.png" height="16" width="16">';
  }

**Comment by ynohtna92** [comment]
Yes you would copy it 4 times obviously changing the text and img src. 

You haven't installed the dependancies my fork requires. Please do these steps.

**Dependencies**
- You're going to need to have (**Windows Only**) [pywin32](http://sourceforge.net/projects/pywin32/) installed. If you run into any errors try running this with (**Linux/OSX Only**)Python [2.7.x](http://www.python.org/download/releases/2.7/).
- [irc 8.5.4](https://pypi.python.org/pypi/irc) - IRC Client
- [Tornado](http://www.tornadoweb.org/en/stable/) - WebSocket Server

**Comment by wreck3d** [comment]
No, i did download the dependencies.
I just put them all in the same folder, but still the same error message.
As you can see, I moved the stuff from /lib folder to the main one, but either way, whether the scrips are in the lib folder or not, still the same error....Do I need to do anything with the IRC & Tornado downloads? I looked at the settings/config files, but didn't really see anything. 
![error](https://cloud.githubusercontent.com/assets/10440098/7672457/b3ea975c-fcc1-11e4-9b94-9094af5b3205.png)

**Comment by ynohtna92** [comment]
That is not how you install python dependencies. Please read the install instructions for each of those dependencies.

When installed correctly you should be able to do the following in the python interpreter without any errors. 
![image](https://cloud.githubusercontent.com/assets/2245318/7672769/e24eaaf4-fd41-11e4-9304-9ed868b12831.png)

**Comment by wreck3d** [comment]
For the IRC install, I'm getting this:
![ircerr](https://cloud.githubusercontent.com/assets/10440098/7672795/d4cdcb2c-fccd-11e4-8e2f-106051cc9d46.png)

**Comment by ynohtna92** [comment]
https://pypi.python.org/pypi/irc/8.5.4 Download this version as it is the one I used.

**Comment by wreck3d** [comment]
Not sure why it keeps saying the setup tools are too old.
![ircer](https://cloud.githubusercontent.com/assets/10440098/7672860/48d8d70c-fcd1-11e4-8184-6e08a5b80140.png)

**Comment by ynohtna92** [comment]
You are not giving the install script a command. It should be 'setup.py install' As for the setuptools error, i cannot help with that.

**Comment by wreck3d** [comment]
That "setup.py install" was all I needed. Installed them both perfectly :+1:

**Comment by wreck3d** [comment]
Alright....so, I got everything running perfectly.
I do, however, have a question on something:
When a directional command (up, down, etc.) is entered, the arrows still do not show.
And nothing shows up when I CTRL+O that "indexhtml" file in the /template folder.
How can I have the arrows show when a direction is commanded?
I currently just have a Window Capture set up on my CMD terminal where the commands come through for my stream.
Thanks!
Oh, & here's how I have the code (starting at line 293 on index file):
EDIT: lol @ my image links getting turned to the actual arrows.

```
    function formatOutput(left, right){
  var buffer_size = 20;
  var buffer_used = 0;
  var whitespace_size = 1;
  var img = "";
```

  if (left == "down"){
  left = " "; // Clear instruction
  img = '<img src="http://i.imgur.com/8QKtaE8.png" height="16" width="16">';
  }

```
if (left == "left"){
```

  left = " "; // Clear instruction
  img = '<img src="http://i.imgur.com/w8lESmr.png" height="16" width="16">';
  }

```
if (left == "right"){
```

  left = " "; // Clear instruction
  img = '<img src="http://i.imgur.com/NyVcb05.png" height="16" width="16">';
  }

```
if (left == "up"){
```

  left = " "; // Clear instruction
  img = '<img src="http://i.imgur.com/CHrpQZD.png" height="16" width="16">';
  }

**Comment by ynohtna92** [comment]
What shows instead?

**Comment by wreck3d** [comment]
The regular full name of the direction.

**Comment by ynohtna92** [comment]
Did you read the instructions? You have to go to http://127.0.0.1:8888 for the UI. The command prompt will only display text.

**Comment by wreck3d** [comment]
I mean, yeah, I did that, but it was showing like 400 days on the timer or something. I'll try it again
And I know the CMD Prompt will only display text, but I didn't know if it got converted to show the image on something...idk what I was thinking :p

EDIT: That IP URL is giving me an error page, which is odd, since I was on it earlier.

**Comment by wreck3d** [comment]
I also have a request for this:
Could you somehow make it so people can enter commands such as:
up3, down2, left6, etc.? Where the number is how many times it'll be pressed.

**Comment by ynohtna92** [comment]
The start time on the timer is hardcoded into index.html, please read above as I have explained how to change it. 

The page will give you an error if the python script has been closed, so it has to stay open. 

Make a request by starting a new issue, but i'm sure aijraj is no longer working on this and neither am I. Sorry but if you want any features you will have to add them yourself, the project is opensource for a reason.

**Comment by wreck3d** [comment]
Alright, will do.
Thank-you.

**Comment by wreck3d** [comment]
Hm...
Ok, so I got the http://127.0.0.1:8888 page open...but when I enter a command, it doesn't show up on that page at all.
![tper](https://cloud.githubusercontent.com/assets/10440098/7674109/82241efa-fcee-11e4-8e70-80df03292881.png)

**Comment by ynohtna92** [comment]
The ircbot is probably not connecting to the channel. You need to make sure that your config https://github.com/ynohtna92/twitch-plays/blob/master/config/config.py has the correct account details and irc settings. The server IP may have changed from when this was made so you might have to go find it.

**Comment by wreck3d** [comment]
Yeah, my config is definitely right.
Where should I start looking for the server IP?

EDIT: Oh wait, in your original config you have the IP at: 199.9.252.26
I changed it to irc.twitch.tv to connect. Should I not have done that?

EDIT2: Changed to the IP above. Made my game stop registering chat commands. Changed back to irc, working again.

**Comment by ynohtna92** [comment]
Looking at it again. formatoutput should be

``` javascript
function formatOutput(left, right){
  var buffer_size = 20;
  var buffer_used = 0;
  var whitespace_size = 1;
  var img = "";

  if (right == "down"){
    right = "  " // Clear instruction
    img = '<img src="downarrow.png" height="16" width="16">'
  }

  buffer_used = right.toString().length + whitespace_size;
  var buffer_left = buffer_size - buffer_used;
  if (buffer_left > left.length) {
    whitespace_size += buffer_left - left.length;
  }
  var left_end = buffer_left;
  left = left.substring(0, left_end);
  return left + Array(whitespace_size + 1).join(" ") + img + right;
};
```

**Comment by wreck3d** [comment]
Not sure what changed from the one you just posted to the original, but I pasted over it in the index.html file, then copy & pasted the code below 6 times, so here's what I have:

```
function formatOutput(left, right){
  var buffer_size = 20;
  var buffer_used = 0;
  var whitespace_size = 1;
  var img = "";

  if (right == "up"){
    right = "  " // Clear instruction
    img = '<img src="http://i.imgur.com/TRWSndF.png" height="16" width="16">'
  }

    if (right == "down"){
    right = "  " // Clear instruction
    img = '<img src="http://i.imgur.com/ZJc5rgj.png" height="16" width="16">'
  }

    if (right == "left"){
    right = "  " // Clear instruction
    img = '<img src="http://i.imgur.com/dCDjvIA.png" height="16" width="16">'
  }

    if (right == "right"){
    right = "  " // Clear instruction
    img = '<img src="http://i.imgur.com/LfjpijV.png" height="16" width="16">'
  }

    if (right == "a"){
    right = "  " // Clear instruction
    img = '<img src="http://i.imgur.com/atGfsuQ.png" height="16" width="16">'
  }

    if (right == "b"){
    right = "  " // Clear instruction
    img = '<img src="http://i.imgur.com/dOzvma1.png" height="16" width="16">'
  }
```

Still not sure why the inputs don't show on the IP URL page, though :/

**Comment by ynohtna92** [comment]
are the commands showing on the cmd? Are there any errors when you press F12 on the page

**Comment by wreck3d** [comment]
Here's my F12 result:
![err](https://cloud.githubusercontent.com/assets/10440098/7674547/6b3eb16e-fcf8-11e4-8976-d018cf3fc801.png)

Red X says:
WebSocket connection to 'ws://localhost:8888/ws' failed: Error during WebSocket handshake: Unexpected response code: 403

EDIT: This shows in CMD every-so-often, but I didn't think anything of it since everything is still working fine.
<img src="http://i.imgur.com/OkWJ4bK.png">

**Comment by ynohtna92** [comment]
The console tab please. Make sure that a couple of commands register in cmd first.

**Comment by wreck3d** [comment]
Yeah, everything regarding CMD Prompt has been fine. Commands register there everytime from multiple people :)

Here's the error (as I edited in above)

![err3](https://cloud.githubusercontent.com/assets/10440098/7674597/9d219b8c-fcf9-11e4-80dc-2c28ac1437eb.png)

EDIT: I view-source'd it and it appear it's on line 171 on the index file

**Comment by ynohtna92** [comment]
Try run it as admin. 403 is an access restriction error.

**Comment by wreck3d** [comment]
I also noticed this just now, if it matters:
And you mean run CMD Prompt as Admin?
![err4](https://cloud.githubusercontent.com/assets/10440098/7674665/4f307b6c-fcfb-11e4-9a82-cddf36b72b7f.png)

**Comment by wreck3d** [comment]
Nope. Still getting the same error

EDIT: I found this: https://github.com/moccu/django-omnibus/pull/25

Would that help? The post says the answer is: to simply add a check_origin method that returns True.
Where would I do that and how?

**Comment by ynohtna92** [comment]
Try add 

```
def check_origin(self, origin):
    return True
```

in lib\web.py after line 16 so it looks like

``` python
class SocketHandler(websocket.WebSocketHandler):

    def check_origin(self, origin):
            return True

    def open(self):
        if self not in cl:
            cl.append(self)

    def on_close(self):
        if self in cl:
            cl.remove(self)
```

**Comment by wreck3d** [comment]
That gave me this:
![err](https://cloud.githubusercontent.com/assets/10440098/7674781/03cf8d3c-fcfd-11e4-8150-29a4f5b9593a.png)

EDIT: nevermind, fixed that. hold on.

EDIT2: Ok, on the IP URL adress, it now says my socket port is open! :D 
Time to test

**Comment by ynohtna92** [comment]
Indentation in that file is wrong now. I used tabs to indent so you will have to remove all the spaces and indent it all with a tab otherwise it will error.

**Comment by wreck3d** [comment]
Yeah, I edited my post (I do that a lot it seems, ha). ^

Alright, the IP URL is now receiving commands!
BUT, the images still aren't showing in place of the directional inputs.

**Comment by wreck3d** [comment]
Here's how I have my index.html set up. Look fine?
![err2](https://cloud.githubusercontent.com/assets/10440098/7674863/5e2753e0-fcfe-11e4-9766-1de2b4958a40.png)

**Comment by ynohtna92** [comment]
It should be working then. You might need to add css for the images so they float instead of going to the end of line. You can verify the img string is being added by inspecting the line of the command.

**Comment by wreck3d** [comment]
Naw, just showing regular directional inputs (up, right, etc) instead of the images.
I mean, it's showing up in the Inspect Element box. Not sure why the image isn't displaying, though.
![err3](https://cloud.githubusercontent.com/assets/10440098/7674969/f8a1abae-fcff-11e4-96a9-298ca2cc9b64.png)

**Comment by wreck3d** [comment]
I want the images to show up exactly where the regular text does. Would I just float right for that?

```
< style>
img {
    float: right;
}
< /style>
```

**Comment by ynohtna92** [comment]
Ok you also have to change the following:

```
input_stream_buffer[17] = json.button.formated;
```

into, to use the method we just made.

```
input_stream_buffer[17] = formatOutput(json.button.user, json.button.button);
```

and just a few lines down

```
$('#' + i).text(input_stream_buffer[i]);
```

to 

```
$('#' + i).html(input_stream_buffer[i]);
```

Then adjust it all with css. Good Luck

**Comment by wreck3d** [comment]
You're a saint, I don't care what anyone tells you, lol.
All I did was edit the lines of code how you said to above and it came out fine without having to edit/add any CSS stuff like you mentioned. :)
![succc](https://cloud.githubusercontent.com/assets/10440098/7681351/913a3394-fd3d-11e4-806f-cd15d0ff44bf.png)

**Comment by wreck3d** [comment]
Hey, new quick question:
This popped up in my CMD Prompt. Any idea how to fix it real quick? First time it's shown.
![err](https://cloud.githubusercontent.com/assets/10440098/7691108/efdbfbd8-fd85-11e4-9772-2d4a2846fb09.png)

**Comment by ynohtna92** [comment]
http://stackoverflow.com/a/11893504 follow this guide.

**Comment by wreck3d** [comment]
Yeah, I know how to add a favicon, but I was just wondering why it's only shown up this one time and not all the other hours I've had the Prompt open (like when I was getting that 403 error). Thanks!
