### ISSUE TITLE
How to set everything up properly?

### ISSUE THREAD

**Issue by Krushchevawn** [aidanrwt/twitch-plays#5]
Okay, so i have Python 2.7 installed. i have my emulator and i have it running and i run serve.py and it said it logs in and the main window is the emulator. is it supposed to make a GUI at all. I was looking around and i saw like chat height and bots and misc and a whole bunch of other stuff. But i still see my standard old emulator nothings different the only thing it did was connect to twitch chat. How do i properly set this up?

**Comment by aidanrwt** [comment]
After someone types a valid button in your chat, it will start printing the username/button pressed and then press the button.

**Comment by Krushchevawn** [comment]
On the Emulator Screen?? Because i tested some commands and it didnt do anything.

**Comment by aidanrwt** [comment]
In your terminal.

Also just to note - >Chat servers are undergoing maintenance. We are doing this one at a time to reduce impact. Thanks for your patience!

**Comment by AUmrysh** [comment]
You can test it out by using a different IRC server than the twitch one and just sending the commands over that. I think the config has a place to set the IRC server, but you can also hardcode it in the irc.py file

**Comment by Krushchevawn** [comment]
So there is no GUI? also what is a good program to stream it with?

**Comment by AUmrysh** [comment]
No GUI (but you could make one and contribute it back to the source if you want!), but there's not really a whole lot to toggle or set up aside from the config file.

I don't know about streaming programs for windows, I use a shell script and do it in linux. Twitch probably recommends some streaming programs for Windows.

**Comment by Krushchevawn** [comment]
Im currently using XSplit Broadcaster, I expierence a 30 second delay, is there anyway to reduce the delay atleast by a little bit?

**Comment by AUmrysh** [comment]
As far as I know, there is a delay introduced by Twitch.tv itself.  Read here for more information:  http://www.neoseeker.com/news/24354-twitch-responds-to-stream-latency-concerns-delays-to-remain-though-twitch-is-aware-and-sympathetic/

**Comment by Krushchevawn** [comment]
Yeah but usually, its about 3-10 seconds. this delay is 30.

**Comment by aidanrwt** [comment]
For streaming windows machines I'd recommend [OBS](http://obsproject.com/). If you need to customize your terminal (fonts and whatnot), I'd recommend using [ConEmu](https://code.google.com/p/conemu-maximus5/).

As for the delay, there's nothing you can do about it. Like AUmrysh said, it was intetionally implemented by Twitch. If you have bad internet it's just going to make it worse.

The delay isn't usually 3-10 seconds. It's usually a lot more than that. It can range anywhere from 20 to 60 seconds based on my experiences.
