### ISSUE TITLE
GUI in the future with this?

### ISSUE THREAD

**Issue by Krushchevawn** [aidanrwt/twitch-plays#6]
Ive had a conversation previously and i was shown a GUI that they used to stream with and i was wondering if this would be included in the future with this and maybe a way to set this up. https://f.cloud.github.com/assets/2245318/2239841/5deb0842-9c5e-11e3-95ee-0d51e547672d.png

I want it to look like that ^ But i have litterally no idea how to get started to set something like that up so does anyone have any input on how to set that up?

**Comment by aidanrwt** [comment]
The web-app that makes use of websockets is available in [ynohtna92's fork](https://github.com/ynohtna92).
